name: jar
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  sqflite: ^2.3.2 # https://pub.dev/packages/sqflite
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  camera: ^0.10.5+9 # https://pub.dev/packages/camera
  firebase_core: ^2.25.4 # https://pub.dev/packages/firebase_core
  google_ml_kit: ^0.16.3
  image_picker: ^1.0.7
  cunning_document_scanner: ^1.1.5
  intl: ^0.17.0

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

