name: jar
description: A new Flutter project.
publish_to: 'none'
version: 0.2.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  sqflite: ^2.3.2 # https://pub.dev/packages/sqflite
  stacked: ^3.4.4
  stacked_services: ^1.6.0
  camera: ^0.10.5+9 # https://pub.dev/packages/camera
  firebase_core: ^2.25.4 # https://pub.dev/packages/firebase_core
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_face_detection: ^0.13.1
  google_mlkit_smart_reply: ^0.13.0
  image_picker: ^1.0.7
  cunning_document_scanner: ^1.1.5
  intl: ^0.17.0
  stacked_hooks: ^0.2.4
  share_plus: ^11.1.0
  file_picker: ^10.3.1
  pdf: ^3.11.3
  package_info_plus: ^8.3.1  
  in_app_update: ^4.2.3

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/background.png
    - assets/images/background_top.png
    - assets/images/background_bottom.png
    - assets/images/body.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#2A9D8F"
  adaptive_icon_foreground: "assets/icon/icon.png"

